### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by vitorsalgado** [MFrederich/java-recruiting-hsa#12]
# Cache
For better performance, we can use a cache strategy to avoid making unecessary calls to remote services or databases. The idea here is to apply a server side cache using **Redis** for both API integrations and to inform consumers to cache resources following HTTP protocol standards.

## Tasks
- [ ] Client Cache. Your API responses must contain cache headers for your resources
- [ ] Configure a local **Redis** to use with your application  
References:  
https://redis.io/
- [ ] Server Side cache using **Redis**  
References:  
https://spring.io/guides/gs/caching/  
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html
