### ISSUE TITLE
Backend for Front End

### ISSUE THREAD

**Issue by vitorsalgado** [MFrederich/java-recruiting-hsa#13]
# Backend for Front End
You need to expose or change your endpoints to return the Top 5 Categories, Remaining Categories and Non Expired Coupons in API call for a client that which uses devices with low process capabilities. 

## Tasks
- [ ] One endpoint returning all required resources in a easy to handle
- [ ] Make the required API calls in parallel 
- [ ] If one API call fails, it should not break all
- [ ] This new endpoint must be documented too
