### ISSUE TITLE
Java Issues

### ISSUE THREAD

**Issue by vitorsalgado** [MFrederich/java-recruiting-hsa#4]
# Java Issues
The code contains general issues and bad practices related to Java that you should fix.

# Tasks
- [x] There are methods declared as public that should not be exposed. Check these methods and change the encapsulation applied to a better one. Eg.:  
[CouponController.java](https://github.com/MFrederich/java-recruiting-hsa/blob/develop/src/main/java/com/concrete/desafio/coupons/CouponController.java).
- [x] Accessing static methods via instance reference. You are accessing the static methods of some components, like [ErrorHandler.java](https://github.com/MFrederich/java-recruiting-hsa/blob/develop/src/main/java/com/concrete/desafio/utils/ErrorHandler.java) via the instance reference.
- [x] Apply **final** keyword everywhere. This avoid unexpected changes in variables and makes your code safer.
- [x] Check unnecessary **empty contructors** in some classes, specially your models.

**Comment by MFrederich** [comment]
pliss, check
