### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vitorsalgado** [MFrederich/java-recruiting-hsa#5]
# Project Documentation
The project needs better documentation to facilitate the communication between developers, newcomers and the ones who will consume your exposed API.

# Tasks
- [x] Swagger for API Documentation.
- [ ] Rewrite the project README.md with a content that explains the pourpose of your project, important topics and links to other documentations that my apply.
- [ ] Create a documentation explaining how to contribute to the project. This documentation may contain code standards, quality rules, minimum coverage, DoD, DoR, git standards and so on. It is better to create this documentation following some standard that your repository already uses.

## Note
The access to your documentation must be easy for anyone.
