### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by vitorsalgado** [MFrederich/java-recruiting-hsa#8]
# Testing
You must improve your test suite to make more reliable and cover more scenarios and component integration. 

## Tasks
- [x] Use a newer version of your test libs like **JUnit 5**
- [ ] Implement integration tests using Spring test libs.  
References:  
https://www.baeldung.com/spring-tests  
https://dzone.com/articles/integration-testing-in-spring-boot-1  
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html
- [x] Apply some coverage report for your project. You may need to change your build scripts. Eg.: Jacoco
- [ ] Create a test strategy simulating API calls using some mock framework for this.  
References:  
http://wiremock.org/docs/java-usage/  
https://www.baeldung.com/mockserver
- [x] **Extra**: Organize your integration tests in a different source set in the project.
